// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvkthrhjlhennplzfuow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2a3RocmhqbGhlbm5wbHpmdW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MDIxMzUsImV4cCI6MjA4NTk3ODEzNX0.8oggXca-2aAapbBN3GWzrbf0vQQRXIJRU9kf6AdKSDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});